name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - healthcheck
    paths-ignore:
      - "LICENSE"
      - "**.md"
  pull_request:
    paths-ignore:
      - "LICENSE"
      - "**.md"

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        base_docker_image: [debian]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python-requirements.txt
        working-directory: test/requirements

      - name: Download docker-gen custom release
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "fabien-marty/docker-gen"
          latest: true
          fileName: "docker-gen-linux-amd64-*.tar.gz"
          tarBall: false
          zipBall: false
          extract: true

      - name: Build Docker web server image
        run: make build-webserver

      - name: Build Docker nginx proxy test image
        run: make build-nginx-proxy-test-${{ matrix.base_docker_image }}

      - name: Run tests
        run: pytest
        working-directory: test
